/**
 * send_audio tool — send audio (and/or DTMF) on an active call.
 * Auto-wires latest generate_audio output if audioSample is omitted.
 */

import type { AgentTool } from '@mariozechner/pi-agent-core';
import { SendAudioConfigSchema, type SendAudioConfig, type TestEvent } from '../validation/schemas.js';
import { getCall } from '../sip/call-store.js';
import { sendAudio } from '../sip/call-session.js';
import { getAudioSamplePath, getLatestSessionSample } from '../sip/audio.js';

export const sendAudioTool: AgentTool = {
  name: 'send_audio',
  label: 'Send Audio',
  description: 'Send audio on an active call. If audioSample is omitted, automatically uses the last audio generated by generate_audio (or voice-hello as fallback). The audio is transcoded to the negotiated codec. Can also send DTMF digits.',
  parameters: SendAudioConfigSchema,

  async execute(toolCallId, params, signal, onUpdate) {
    const config = params as SendAudioConfig;
    const handle = getCall(config.callId);

    if (!handle) {
      return {
        content: [{ type: 'text', text: `No active call with ID: ${config.callId}` }],
        details: { error: 'call_not_found', callId: config.callId },
      };
    }

    // Resolve audio sample: explicit → latest session-generated → built-in voice-hello
    const sample = config.audioSample || getLatestSessionSample() || 'voice-hello';
    const samplePath = getAudioSamplePath(sample);

    if (!samplePath && !config.dtmfDigits) {
      return {
        content: [{ type: 'text', text: `Audio sample not found: ${sample}. Generate audio first with generate_audio, or specify dtmfDigits.` }],
        details: { error: 'audio_not_found', sample },
      };
    }

    const events: TestEvent[] = [];
    const t0 = Date.now();

    const emit = (ev: TestEvent) => {
      events.push(ev);
      const elapsed = `+${((ev.timestamp - t0) / 1000).toFixed(3)}s`;
      onUpdate?.({
        content: [{ type: 'text', text: `[${ev.type.toUpperCase()}] ${elapsed} ${ev.message}` }],
        details: { event: ev },
      });
    };

    try {
      await sendAudio(handle, samplePath, emit, config.dtmfDigits);

      const summary = samplePath
        ? `Audio sent (${sample}) as ${handle.negotiatedCodec.name}`
        : `DTMF sent: ${config.dtmfDigits}`;

      return {
        content: [{ type: 'text', text: summary }],
        details: { callId: config.callId, sample, events },
      };
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Failed to send audio: ${error instanceof Error ? error.message : String(error)}` }],
        details: { error: error instanceof Error ? error.message : String(error), events },
      };
    }
  },
};
